---
title: "Aid Doesn't Follow Need"
subtitle: "Delaware's School Funding Formula"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r constants}
INDIR = here::here("viz", "input")
INFILE = here::here("clean", "output", "final.csv")
IN_SHP = here::here("clean", "output", "final.geojson")
```

```{r libs}
library(dplyr)
library(ggplot2)
library(glue)
library(here)
library(readr)
library(scales)
library(sf)
library(stringr)
library(tidyr)
source(here::here("viz", "src", "plot_utils.R"), local = TRUE)
source(here::here("viz", "src", "leaflet_utils.R"), local = TRUE)
```

```{r data, include=FALSE}
data =
  readr::read_csv(INFILE) %>%
  dplyr::select(
    district,
    fall_enrollment,
    pct_fall_enrollment_low_income,
    opp_funding_pp,
    state_revenue_pp,
    local_revenue_pp,
    state_local_revenue_pp,
    state_local_opp_revenue_pp
  )
data_long = data %>%
  tidyr::pivot_longer(c(state_revenue_pp, local_revenue_pp)) %>%
  dplyr::mutate(
    name = dplyr::recode_factor(
      name,
      "state_revenue_pp" = "State",
      "local_revenue_pp" = "Local"
    )
  )
data_long_opp = data %>%
  tidyr::pivot_longer(c(opp_funding_pp, state_revenue_pp, local_revenue_pp)) %>%
  dplyr::mutate(
    name = dplyr::recode_factor(
      name,
      "opp_funding_pp" = "Opportunity",
      "state_revenue_pp" = "State",
      "local_revenue_pp" = "Local"
    )
  )
sd = sf::st_read(IN_SHP)
```

## Overview

```{r global_features}
y_lab = "Total revenue per pupil (2018-19)"
x_lab = "Low Income (% of Fall enrollment)"
caption_bar = glue::glue("Labels: {x_lab}")
palette =  c("#7CAE00", "#00BFC4")
palette_opp = c("#F8766D", palette)
tooltip = "District: <b>{data$district}</b>
  Total revenue per pupil: <b>{scales::dollar(data$state_local_revenue_pp)}</b>
  State revenue per pupil: <b>{scales::dollar(data$state_revenue_pp)}</b>
  Local revenue per pupil: <b>{scales::dollar(data$local_revenue_pp)}</b>
  Fall enrollment: <b>{cma(data$fall_enrollment)}</b>
  Low income: <b>{pct(data$pct_fall_enrollment_low_income)}</b>"
```

```{r scatter_revenue_lowincome}
p = data %>%
  ggplot2::ggplot(
    ggplot2::aes(
      x = pct_fall_enrollment_low_income,
      y = state_local_revenue_pp,
      size = fall_enrollment,
      color = district,
      text = glue::glue(tooltip)
    )
  ) +
  ggplot2::geom_point() +
  add_theme() +
  ggplot2::scale_x_continuous(labels = pct) +
  format_y_axis() +
  ggplot2::guides(size = FALSE, color = FALSE) +
  ggplot2::labs(x = x_lab, y = y_lab)
plotly::ggplotly(p, tooltip = "text") %>%
  plotly::hide_guides()
```

***

```{r bar_revenue}
data_long %>%
  dplyr::rename(y_var = state_local_revenue_pp) %>%
  stacked_bar_revenue(title = "", palette = palette)
```

***

```{r bar_revenue_opp}
# data_long_opp %>%
#   dplyr::rename(y_var = state_local_opp_revenue_pp) %>%
#   stacked_bar_revenue(
#     title = "Opportunity funding won't address need",
#     palette = palette_opp
#   )
```

***

```{r}
data = sd
tooltip = stringr::str_replace_all(tooltip, c("\\n" = "<br>"))
make_leaflet(
  data,
  shade_var = data$state_local_revenue_pp,
  title = "Total revenue<br>per pupil",
  tooltip = glue::glue(tooltip),
  legend_label_prefix = "$"
)
```

***

## Data Sources

- Revenue per pupil: *Educational Statistics Report* (2018-19)

- Low income enrollment, Fall enrollment: *Open Data Delaware* (2018-19)

*Note:* Enrollment in the *Educational Statistics Report* matches enrollment on Open Data Delaware for 2018-19, *except for* Caesar Rodney and Red Clay school districts.
